# Generated by Django 4.0.5 on 2022-06-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Mostar',
            new_name='Mostrar',
        ),
    ]
